#!/bin/dash

# feh Pictures/Wallpapers/purp1.jpg --bg-scale &
# dash ~/.bin/clockskewcheck &
# feh ~/Media/Wallpapers/4k.png --bg-scale &
nitrogen --restore &
# xmodmap ~/.keymaps/tarmak_2b_dh.xmodmap &
xrdb ~/.config/suckless/mocha && killall -USR1 st &
pkill volumeicon; volumeicon &

# pkill picom; picom &
